### PR TITLE
Use empty over count on string for PHP 7.2 compat

### PR DESCRIPTION
**Pull request by andrerom**

### CODE REVIEW

**Comment by derickr** [comment]
What's wrong with ``!count()`` in PHP 7.2?

**Comment by andrerom** [comment]
`PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/travis/build/ezsystems/ezpublish-legacy/vendor/zetacomponents/database/src/factory.php on line 268`

https://wiki.php.net/rfc/counting_non_countables

**Comment by derickr** [comment]
Would you mind rebasing this on master and force pushing your branch. I've just added Travis so that it gets tested and you're the guinea pig :-)

**Comment by derickr** [comment]
Whoop! First fully green one: https://travis-ci.org/zetacomponents/Database/builds/280467974

I'd like a rebase onto master anyway, otherwise GitHub doesn't necessarily see I merged your patch.

**Comment by andrerom** [comment]
> otherwise GitHub doesn't necessarily see I merged your patch.

either you or I overlooking something on how merges work in Git, but even if I don't think it is needed or makes a difference; ok :)

**Comment by andrerom** [comment]
Rebased ;)

**Pull request merged**
